const clothingSet = new Set([
    "Sari",
    "Salwar Kameez",
    "Lehenga Choli",
    "Anarkali Suit",
    "Churidar",
    "Kurta Pajama",
    "Sherwani",
    "Dhoti",
    "Pathani Suit",
    "Bandhgala",
    "Chaniya Choli",
    "Ghagra Choli",
    "Patiala Suit",
    "Phulkari",
    "Mundu",
    "Kasavu Sari",
    "Pancha",
    "Kanjivaram Sari",
    "Banarasi Sari",
    "Pashmina Shawl",
    "Turban",
    "Dupatta",
    "Stole",
    "Mekhela Chador",
    "Assamese Sari",
    "Kurti",
    "Punjabi Suit",
    "Rajputi Poshak",
    "Pagdi",
    "Angarkha",
    "Bhagalpuri Sari",
    "Gota Patti Sari",
    "Pheta",
    "Bandhani Sari",
    "Chikankari",
    "Patola Sari",
    "Kosa Sari",
    "Sherwani",
    "Jodhpuri Suit",
    "Dungarees",
    "Pheran",
    "Langota",
    "Kasuti Sari",
    "Kutch Embroidery",
    "Mysore Silk Sari",
    "Kalamkari",
    "Kasavu Mundu",
    "Kerela Sari",
    "Chak Bandh Sari",
    "Choli",
    "Lungi",
    "Madisar",
    "Nauvari Sari",
    "Odisha Sari",
    "Bomkai Sari",
    "Kandyan Sari",
    "Gagra",
    "Pavadai",
    "Rajasthani Turban",
    "Shervani",
    "Sherwani",
    "Ghaghara",
    "Lugda",
    "T-shirt",
    "Jeans",
    "Sweater",
    "Dress",
    "Skirt",
    "Blouse",
    "Shorts",
    "Pants",
    "Jacket",
    "Coat",
    "Shirt",
    "Hoodie",
    "Scarf",
    "Hat",
    "Gloves",
    "Socks",
    "Shoes",
    "Boots",
    "Sandals",
    "Heels",
    "Flip-flops",
    "Sunglasses",
    "Belt",
    "Handbag",
    "Backpack",
    "Watch",
    "Necklace",
    "Bracelet",
    "Earrings",
    "Ring",
    "Cap",
    "Tie",
    "Pajamas",
    "Lingerie",
    "Swimsuit",
    "Robe",
    "Tights",
    "Ankle socks",
    "Beanie",
    "Pullover",
    "Vest",
    "Polo shirt",
    "Sweatshirt",
    "Clogs",
    "Loafers",
    "Moccasins",
    "Brogues",
    "Polo neck",
    "Hijab",
    "Kimono",
    "Cape",
    "Tunic",
    "Bowtie",
    "Blazer",
    "Waistcoat",
    "Turtleneck",
    "Cardigan",
    "bangles",
    "noserings",
    "earrings"

  ]);

  export default clothingSet;